# WEB BACKEND Reference
*Last Updated: 2025-12-06 15:25:08*
*Generated by Granite 4.0 Local Librarian*

---

## File: `deprecated\server.py`

# Deprecated Server API Contract

## CORS Middleware
- Allows CORS for frontend communication
- `allow_origins=["*"]`: Allow all origins
- `allow_credentials=True`: Allow credentials
- `allow_methods=["*"]`: Allow all HTTP methods
- `allow_headers=["*"]`: Allow all headers

## Routes and Endpoints

### `/api/instructions/{model_name}` (GET)
- **Parameters**:
  - `model_name` (path): String representing the model name
  - `project_directory` (query): Optional string representing the project directory
- **Response**:
  - `200 OK`: Returns the content of the instruction file for the specified model
  - `404 Not Found`: If the model is not found in `INSTRUCTION_FILES`

### `/api/instructions/{model_name}` (POST)
- **Parameters**:
  - `model_name` (path): String representing the model name
  - `instruction_file` (body): `InstructionFile` model containing the content and optional project directory
- **Response**:
  - `200 OK`: Returns a success message if the file is saved successfully
  - `404 Not Found`: If the model is not found in `INSTRUCTION_FILES`
  - `500 Internal Server Error`: If there's an error saving the file

### `/api/fs/browse` (POST)
- **Parameters**:
  - `directory_path` (body): `DirectoryPath` model containing the directory path
- **Response**:
  - `200 OK`: Returns the contents of the specified directory
  - `400 Bad Request`: If the provided directory path is invalid
  - `500 Internal Server Error`: If there's an error browsing the directory

### `/api/fs/create-folder` (POST)
- **Parameters**:
  - `new_folder` (body): `NewFolder` model containing the path and folder name
- **Response**:
  - `200 OK`: Returns a success message if the folder is created successfully
  - `400 Bad Request`: If the folder name already exists in the specified path
  - `500 Internal Server Error`: If there's an error creating the folder

## Models

### `InstructionFile`
- `content` (required): String representing the content of the instruction file
- `project_directory` (optional): String representing the project directory

### `DirectoryPath`
- `path` (required): String representing the directory path

### `NewFolder`
- `path` (required): String representing the path where the new folder will be created
- `folderName` (required): String representing the name of the new folder

## Data Flow

1. The client sends a request to one of the available endpoints.
2. The server receives the request and validates the input parameters based on the defined models.
3. The server processes the request:
   - For `GET /api/instructions/{model_name}`, it reads the instruction file content from the specified path and returns it.
   - For `POST /api/instructions/{model_name}`, it saves the provided instruction file content to the specified path.
   - For `POST /api/fs/browse`, it browses the specified directory and returns its contents.
   - For `POST /api/fs/create-folder`, it creates a new folder with the specified name in the given path.
4. The server sends the appropriate response back to the client based on the request and processing result.

## Notes
- The `INSTRUCTION_FILES` dictionary maps model names to their corresponding file paths.
- The `base_path` is determined based on the provided `project_directory` or defaults to the parent directory of the current file.
- Error handling is implemented using `HTTPException` to return appropriate status codes and error messages.

---

